# Generated by Django 6.0.3 on 2026-04-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saheb', '0004_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('provider_order_id', models.CharField(max_length=40, verbose_name='Order ID')),
                ('payment_id', models.CharField(max_length=36, verbose_name='Payment ID')),
                ('signature_id', models.CharField(max_length=128, verbose_name='Signature ID')),
                ('status', models.BooleanField(default=False, verbose_name='Payment Status')),
            ],
        ),
    ]
