# Generated by Django 6.0.3 on 2026-04-18 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saheb', '0005_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
