"""
Django settings for maa project.
Generated by 'django-admin startproject' using Django 6.0.3.
"""

from pathlib import Path 
import os, dj_database_url


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-pv_daq98k64f_7s$t)9#mpiy#5bo1#d&o1%pw1nq0kb@vnl^3h'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True 

ALLOWED_HOSTS = ["*"]

CSRF_TRUSTED_ORIGINS = [
    'https://*.pythonanywhere.com',
    'https://*.onrender.com'
]

# Application definition
INSTALLED_APPS = [
    'saheb', # Aapka main app sabse upar
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary_storage', # Isko staticfiles ke niche rakha hai taaki clash na ho
    'cloudinary',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'maa.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'maa.wsgi.application'

# --- DATABASE SETUP (NEON.TECH) ---
# Agar Render par DATABASE_URL milega, toh Neon use karega, warna local SQLite
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

DATABASES = {
    'default': dj_database_url.parse('postgresql://neondb_owner:npg_7puQz1vSjJgf@ep-bold-flower-ao8pe48h-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require')
    # 'default': dj_database_url.parse('postgresql://neondb_owner:npg_sSFPcQ09ukgd@ep-orange-forest-am8ansqx-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require')
}

if 'DATABASE_URL' in os.environ:
    DATABASES['default'] = dj_database_url.parse(os.environ.get('DATABASE_URL'))

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# --- STATIC FILES (CSS, JS) ---
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')] 
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# --- MEDIA FILES ---
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# --- CLOUDINARY CREDENTIALS ---
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': 'dz7trcsew', 
    'API_KEY': '673284384824469', 
    'API_SECRET': 'YLWPimM-bAon69TPfJHy_1hcHZI',
    'SECURE': True
}
# CLOUDINARY_STORAGE = {
#     'CLOUD_NAME': 'dpddeluej', 
#     'API_KEY': '769561459113556', 
#     'API_SECRET': 'l9NcXJIpafg6Z6iMBiFRp4qCv6U',
#     'SECURE' : True
# }

# --- THE MAGIC FIX FOR CLOUDINARY + DJANGO 6.0 ---
# 1. Dummy variable taaki Render par Cloudinary package crash na ho
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

# 2. Real variable naye Django ke liye (Jo asli kaam karega)
STORAGES = {
"default": {
    # NAYA RASTA: Jo photo aur video dono accept karega
    "BACKEND": "saheb.storage.AutoMediaCloudinaryStorage",
},
    "staticfiles": {
        # Normal CSS/JS save karo (Taaki 'uk.js' wala error wapas na aaye)
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}