"""
Django settings for maa project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path 
import os ,dj_database_url
 
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-pv_daq98k64f_7s$t)9#mpiy#5bo1#d&o1%pw1nq0kb@vnl^3h'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True #------------------------------------------------------------------------------------------
ALLOWED_HOSTS = ["*"]
# ALLOWED_HOSTS = [ '192.168.0.104' , 'localhost','127.0.0.1']/

CSRF_TRUSTED_ORIGINS = [
    'https://*.pythonanywhere.com'
]

# Application definition

INSTALLED_APPS = [
    'cloudinary_storage',
    'cloudinary',
    'saheb',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'maa.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'maa.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
# Agar Render par DATABASE_URL milega, toh Neon use karega, warna local SQLite
if 'DATABASE_URL' in os.environ:
    DATABASES['default'] = dj_database_url.parse(os.environ.get('DATABASE_URL'))

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
# --- STATIC FILES (CSS, JS) FOR LIVE SERVER ---
STATIC_URL = '/static/'

# YEH NAYI LINE: Django ko bata rahe hain ki aapki original CSS/JS kahan rakhi hai
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')] 

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# extra add on 
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Razorpay Test Keys
RAZORPAY_KEY_ID = 'rzp_test_SYCLG4Bb32H8Gm'
RAZORPAY_KEY_SECRET = 'z7mnRkdMd2WZJFt47TY58ri1'

# --- CLOUDINARY CREDENTIALS FOR LOCAL VS CODE ---
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': 'dpddeluej', # Aapka cloud name
    'API_KEY': '769561459113556', # Aapki API Key
    'API_SECRET': 'Yl9NcXJIpafg6Z6iMBiFRp4qCv6U' # Apna API Secret yahan paste karo
}

# --- NAYA DJANGO STORAGE SYSTEM ---
STORAGES = {
    "default": {
        # Yeh aapki Photos/Videos ko hamesha Cloudinary mein bhejega
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        # Yeh CSS/JS design files ke liye hai
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}